version: '3.1'
services:
  postgres:
    container_name: local-postgres
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_DB=social-media-api
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - 'data:/var/lib/postgresql/data'
    image: postgres
  api:
    container_name: local-app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost/social-media-api
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    ports:
      - '8080:8080'
    image: social-media-api:1.0

